### ISSUE TITLE
Tangled chains example fails on unrooted tree

### ISSUE THREAD

**Issue by alexweisberg** [blab/baltic#11]
I am trying the "tangled chains" example code from the austechia notebook (https://github.com/evogytis/baltic/blob/master/austechia.ipynb) using my own trees, and I am running into an issue. 
The trees are generic unrooted trees generated by RAxML (ie not time trees). I would like to plot them in essentially a cophylo plot however with all of the trees displayed at once as in the example. I've attached the code and trees. The code is copied and pasted from the python notebook with the exception that the trees are parsed with make_tree and tree_traverse.
[example.tar.gz](https://github.com/blab/baltic/files/2734530/example.tar.gz)

When running in Python 2.7, it reaches the line:
> leaves=[[seg.tipMap[tip] for tip in w.leaves] if w.branchType=='node' else [w.name] for w in k.children] ## descendent tips in current order

I get the error:
>   File "makeallcophylo_py2.py", line 68, in <module>
    leaves=[[seg.tipMap[tip] for tip in w.leaves] if w.branchType=='node' else [w.name] for w in k.children] ## descendent tips in current order
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by evogytis** [comment]
There's a few things going wrong here. First of all, you're using trees that have non-overlapping taxa and the code I wrote was never meant to handle it. Second, you should root your trees consistently which looks possible given that there's always a diverged clade. The code you posted failed because it called `seg.tipMap`, a dictionary that maps encoded tip names (numbers) to their full names in BEAST trees (and which remains `None` unless a nexus file is given). There were some other mistakes in the code, like not calling `drawTree()` to calculate `y` positions of tips and logging tip locations under `k.name` which is `None` (`k.numName` should be used).

The following are snippets that I modified to make it run, but it fails upon second the second tree because taxa are not shared between trees.

```
    ll=myTree
    ll.traverse_tree()
    ll.drawTree() ## add this
    print(tree_path.split('.')[0])
```

```
for t,tr in enumerate(trees.keys()): ## iterate over trees
    cur_tree=trees[tr] ## fetch tree object
    for k in cur_tree.Objects:
        if k.branchType=='leaf':
            tip_positions[tr][k.numName]=(k.height,k.y) ## remember XY position of tip (changed k.name to k.numName)

cmap=mpl.cm.Spectral
```

```
            if k.branchType=='node': ## can only sort nodes
                # print(k.children)
                # leaves=[[seg.tipMap[tip] for tip in w.leaves] if w.branchType=='node' else [w.name] for w in k.children] ## descendent tips in current order
                leaves=[w.leaves if w.branchType=='node' else [w.numName] for w in k.children] ## descendent tips in current order (changed call to tipMap, changed w.name to w.numName)

                for c in range(len(leaves)):
                    leaves[c]=sorted(leaves[c],key=lambda x:tip_positions[ntr][x][1])
```

**Comment by alexweisberg** [comment]
Thank you! I realized just before you replied that if I convert my trees to nexus format and slightly modify them and the regular expressions, I can load them using loadNexus. I've been modifying the rest of the iteration/display code to work with incomplete taxa sets. Thank you for the help and suggestions!

**Comment by evogytis** [comment]
Hey @alexweisberg, the last update to baltic + `austechia.ipynb` should now work with trees that don't have completely overlapping taxon sets. Note that all future development of baltic will happen on my repo now: https://github.com/evogytis/baltic

**Comment by alexweisberg** [comment]
Thank you for adding that feature! I will check it out at the new repo.
